apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nodejs
  namespace: default
spec:
  rules:
    - host: 
      http:
        paths:
          - path: /nodejs
            backend:
              serviceName: ecsdemo-nodejs
              servicePort: 80
